[project]
name = "lakehouse-lakekeeper"
version = "0.1.0"
description = "A Sample Project Setting Up Lakekeeper with Spark/PyIceberg/Trino/Starocks"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
